name: dollar_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.7.1
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_database: ^10.2.1
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  flutter_scroll_to_top: ^2.3.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.6.2
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  go_router: ^7.0.1
  google_fonts: ^4.0.4
  heroicons: ^0.8.0
  http: ^0.13.6
  image_picker: ^0.8.7+5
  syncfusion_flutter_charts: ^21.2.8
  syncfusion_flutter_datepicker: ^21.2.5
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/receipt_1.png
    - assets/images/receipt_2.jpg
    - assets/sample_data.json
    - assets/images/market.jpg
    - assets/images/no_image.png
